/* Brno University of Technology
 * Faculty of Information Technology
 *
 * BSc Thesis  2006/2007
 *
 * Railway Interlocking Simulator
 *
 * Bedrich Hovorka
 */
package cz.vutbr.fit.interlockSim.dispatcher.agents

import cz.vutbr.fit.interlockSim.dispatcher.ValidationVerdict
import cz.vutbr.fit.interlockSim.dispatcher.observation.AppliedOutcome

/**
 * Immutable record of a single dispatcher tick's inputs and outputs, stored in the
 * [TickRingBuffer] for rendering in the RECENT TICKS prompt section (SP2c.7, Issue #830).
 *
 * This type is **distinct** from [cz.vutbr.fit.interlockSim.dispatcher.planner.TickRecord],
 * which carries only the planner-level [cz.vutbr.fit.interlockSim.dispatcher.planner.TickOutcome]
 * taxonomy. This ring-buffer record carries the full action/verdict/outcome triple needed for
 * deterministic context construction (axis E3 / E5 from Issue #822).
 *
 * ## Determinism (P8)
 *
 * Every field is a **pure function of the recorded action sequence and the simulation
 * observation**. Nothing is LLM-generated; nothing is free-form. Two records built from the
 * same inputs are structurally `==` (Kotlin data-class equality), so rendering the same
 * [TickRingBuffer.snapshot] produces byte-identical output.
 *
 * ## Bounded size
 *
 * The [actions] list is capped at 3 entries per tick (the per-tick action limit checked by
 * [cz.vutbr.fit.interlockSim.dispatcher.ActionValidator.validateBatch]).
 * The [verdicts] list is parallel to [actions] and therefore equally bounded.
 * The [outcomes] list is bounded by the number of actuator commands drained this tick (also ≤ 3).
 * The rendered size therefore has a hard character ceiling asserted by
 * `TickRingBufferTest.renderedRecentTicksBlockWithinCharCeiling`.
 *
 * @property tick Dispatcher tick number at which this record was created. Monotonically
 *   increasing; matches [cz.vutbr.fit.interlockSim.dispatcher.observation.DispatcherObservation.tick].
 * @property simTime Simulation time (seconds) at the start of this tick.
 * @property stateDigest Content hash of the [cz.vutbr.fit.interlockSim.dispatcher.observation.DispatcherObservation]
 *   captured this tick, computed via [cz.vutbr.fit.interlockSim.dispatcher.observation.DispatcherObservation.digest].
 *   Two ticks with identical digests saw an identical railway state.
 * @property actions Actions emitted by the dispatcher this tick (attributed with a
 *   [cz.vutbr.fit.interlockSim.dispatcher.CommandId] via [AttributedAction]).
 *   Empty when the dispatcher decided to do nothing ([DispatchAction.NoOp][cz.vutbr.fit.interlockSim.dispatcher.DispatchAction.NoOp]
 *   is stored here only if the LLM explicitly emitted it).
 * @property verdicts Parallel list to [actions]; `verdicts[i]` is the validation verdict for
 *   `actions[i]`. Always the same length as [actions].
 * @property outcomes [AppliedOutcome]s that arrived **this tick** — correlated back from the
 *   actuator side-channel for actions emitted on PREVIOUS ticks. Includes any TTL-expiry
 *   synthetic drops (`description = "DROPPED_NO_OUTCOME"`) generated by [WorkingMemory.update].
 *
 * @see TickRingBuffer
 * @see WorkingMemory
 * @since Issue #830 (SP2c.7 — Goal 10 ring buffer)
 */
data class TickRecord(
	val tick: Long,
	val simTime: Double,
	val stateDigest: String,
	val actions: List<AttributedAction>,
	val verdicts: List<ValidationVerdict>,
	val outcomes: List<AppliedOutcome>
) {
	init {
		require(actions.size == verdicts.size) {
			"actions and verdicts must be parallel lists: " +
				"actions.size=${actions.size} verdicts.size=${verdicts.size}"
		}
	}
}
