{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kdisco-core/0.5.0/kdisco-core-0.5.0.module",
    "group": "cz.hovorka.kdisco",
    "module": "kdisco-core",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kdisco-core-jvm-0.5.0.jar",
          "url": "kdisco-core-jvm-0.5.0.jar",
          "size": 60740,
          "sha512": "92c6b1119e473fa982dfbd8d37cf11aaffc042fb629bf8c81b2de1ec7a69bbb1e444311269d3c5e4c6d8f337b84a69cbae9bbcca2ee619a1c4b2310ffb232b84",
          "sha256": "e72def89f1d37bd61bc9e889066c37be2e241e4da4ffb4fc05c17d3f40119e23",
          "sha1": "5bbdbc65fc4ab513dca2b7810b38f7eeabfb3432",
          "md5": "c39d4ccd2ed904d557b4461cce7edfe7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kdisco-core-jvm-0.5.0.jar",
          "url": "kdisco-core-jvm-0.5.0.jar",
          "size": 60740,
          "sha512": "92c6b1119e473fa982dfbd8d37cf11aaffc042fb629bf8c81b2de1ec7a69bbb1e444311269d3c5e4c6d8f337b84a69cbae9bbcca2ee619a1c4b2310ffb232b84",
          "sha256": "e72def89f1d37bd61bc9e889066c37be2e241e4da4ffb4fc05c17d3f40119e23",
          "sha1": "5bbdbc65fc4ab513dca2b7810b38f7eeabfb3432",
          "md5": "c39d4ccd2ed904d557b4461cce7edfe7"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kdisco-core-jvm-0.5.0-sources.jar",
          "url": "kdisco-core-jvm-0.5.0-sources.jar",
          "size": 23654,
          "sha512": "fc635678396c5d9ad587cddca380b7d9af467000c077d5617f9c6cd876066d4c360045b8f549cb4fbe5cee605de9454423768c1336ffc0922c9602d550f6e345",
          "sha256": "7bd0071004c86d1b42b957bf04f0f63111ae52b1f7ebda5f65a281f58b5163d3",
          "sha1": "7603febaa8bc1ea97268c8af86f6629ce0e71776",
          "md5": "e303eb218000010fcbed6690a7d450de"
        }
      ]
    }
  ]
}
