{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kdisco-core/0.4.0/kdisco-core-0.4.0.module",
    "group": "cz.hovorka.kdisco",
    "module": "kdisco-core",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kdisco-core-linuxX64Main-0.4.0.klib",
          "url": "kdisco-core-linuxx64-0.4.0.klib",
          "size": 80170,
          "sha512": "7b1da73ea6783f5fe580fc0c51d48acba0658ccd8eb4eba023c7ad3c02eefe8e86ad1b295be3796ff48f758ccdf724bf6b3045957e8dbfcc3ba6443e697887a8",
          "sha256": "d6981e0f15f9577d4bd65c2dfb76f676c189bbf4b3e01ba2048cd39cb23a6836",
          "sha1": "1ed63f58252e8b33a13c2285e4466078de80f8ad",
          "md5": "ff659e0e6e76d6e8f41bd1cab730552e"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kdisco-core-linuxx64-0.4.0-sources.jar",
          "url": "kdisco-core-linuxx64-0.4.0-sources.jar",
          "size": 24475,
          "sha512": "6b09bb79d12faab8ad2f0d7ba69b2cb48744e05997e6a645365072622e1c711cee2f7b95b413b5c6f6435ae60e75d1fa6fa27c9892bf43c2b6d0ce7bdbd6a6b4",
          "sha256": "fb31e5309bce22d62673a4d6f7a709a63d6ec9d4d80a45a77e438e5644249d20",
          "sha1": "97774148162ee2ced6ba08893f42e118b216c95e",
          "md5": "e58e5f597ab1530b65f650edda656d04"
        }
      ]
    }
  ]
}
