/* Brno University of Technology
 * Faculty of Information Technology
 *
 * BSc Thesis  2006/2007
 *
 * Railway Interlocking Simulator
 *
 * Bedrich Hovorka
 */
package cz.vutbr.fit.interlockSim.objects.cells

import cz.vutbr.fit.interlockSim.exceptions.requireSimulation
import cz.vutbr.fit.interlockSim.objects.cells.RailSwitch.Type
import cz.vutbr.fit.interlockSim.util.EnumUnorientedGraph
import io.github.oshai.kotlinlogging.KotlinLogging
import java.util.EnumMap
import java.util.EnumSet

/**
 * Switch
 * CZ: "výhybka"
 */
class RailSwitch : NodeCell {
	enum class Kind(
		confs: Set<Conf>
	) {
		/**
		 * switch with one branch
		 */
		SIMPLE(EnumSet.of(Conf.BRANCH, Conf.MAIN) as Set<Conf>),

		/**
		 * not specified
		 */
		DUAL(EnumSet.noneOf(Conf::class.java) as Set<Conf>); // NOT IMLEMENTED YET - EXTENSION

		@Suppress("UNCHECKED_CAST")
		private val possibleConfs: Set<Conf> = confs

		fun getPossibleConfs(): Set<Conf> = possibleConfs
	}

	enum class Conf {
		/**
		 * main directon
		 */
		MAIN,

		/**
		 * branch direction
		 */
		BRANCH
	}

	/**
	 *
	 * Type "smer odbocky"
	 *
	 */
	enum class Type(
		mergingOrientation: Boolean
	) {
		/**
		 *
		 */
		SIMPLE_RIGHT_FALSE(false),

		/**
		 *
		 */
		SIMPLE_RIGHT_TRUE(true),

		/**
		 *
		 */
		SIMPLE_LEFT_FALSE(false),

		/**
		 *
		 */
		SIMPLE_LEFT_TRUE(true);

		private val mergingPosition: Boolean
		private val kind: Kind

		init {
			// constructor only for simple kinds
			this.mergingPosition = mergingOrientation
			this.kind = Kind.SIMPLE
		}

		/**
		 * @return merging position (by simple kind)
		 */
		fun getMergingPosition(): Boolean = mergingPosition

		fun getKind(): Kind = kind
	}

	val speeds: EnumMap<Conf, Double> = EnumMap<Conf, Double>(Conf::class.java)
	val confs: EnumUnorientedGraph<Cell.Segment, Conf>
	val type: Type

	/**
	 * @param spatialType
	 * @param type
	 * @param mainSpeed
	 * @param branchSpeed
	 */
	constructor(
		spatialType: Cell.SpatialType,
		type: Type,
		mainSpeed: Double,
		branchSpeed: Double
	) : super(spatialType) {
		this.confs = allConfs.get(type, spatialType)
			?: throw IllegalArgumentException(UNSUPORTED_SWITCH_TYPES_MESSAGE)
		this.type = type
		speeds.put(Conf.BRANCH, branchSpeed)
		speeds.put(Conf.MAIN, mainSpeed)
	}

	/**
	 * @param spatialType
	 * @param type
	 */
	constructor(
		spatialType: Cell.SpatialType,
		type: Type
	) : this(spatialType, type, COMMON_MAIN_SPEED.toDouble(), COMMON_BRANCH_SPEED.toDouble())

	// Note: getType() is auto-generated by the 'val type' property

	@Suppress("OVERRIDE_BY_SYNTHETIC")
	override fun joins(): Set<Cell.Segment> {
		// Parent Cell interface expects Set, and joinsOnLine() returns MutableSet
		val joins = joinsOnLine()
		joins.addAll(getBranchSegments())
		return joins
	}

	/**
	 * @return directions of branchs
	 */
	fun getBranchSegments(): Set<Cell.Segment> = getBranchSegments(this)

	@Suppress("OVERRIDE_BY_SYNTHETIC")
	override fun possibleFollowers(from: Cell.Segment): Set<Cell.Segment> {
		val map = confs.getJoinedNodesAndEdges(from)
		@Suppress("UNCHECKED_CAST")
		return (map as Map<Cell.Segment, *>).keys
	}

	companion object {
		init {
			putBranches()
		}
	}
}

private class SwitchMap<V> : EnumMap<Type, EnumMap<Cell.SpatialType, V>>(Type::class.java) {
	fun put(
		t: Type,
		st: Cell.SpatialType,
		v: V
	) {
		var subMap = get(t)
		if (subMap == null) {
			subMap = EnumMap<Cell.SpatialType, V>(Cell.SpatialType::class.java)
			put(t, subMap)
		}
		subMap.put(st, v)
	}

	fun get(
		t: Type,
		st: Cell.SpatialType
	): V? {
		val subMap = get(t)
		if (subMap == null) return null
		return subMap.get(st)
	}
}

private val logger = KotlinLogging.logger {}

/**
 * allowed speed
 * @deprecated Use [cz.vutbr.fit.interlockSim.domain.COMMON_BRANCH_SPEED] from domain.PhysicsConstants
 */
@Deprecated(
	"Use COMMON_BRANCH_SPEED from domain.PhysicsConstants",
	ReplaceWith("COMMON_BRANCH_SPEED", "cz.vutbr.fit.interlockSim.domain.COMMON_BRANCH_SPEED")
)
const val COMMON_BRANCH_SPEED = cz.vutbr.fit.interlockSim.domain.COMMON_BRANCH_SPEED

/**
 * allowed speed
 * @deprecated Use [cz.vutbr.fit.interlockSim.domain.COMMON_MAIN_SPEED] from domain.PhysicsConstants
 */
@Deprecated(
	"Use COMMON_MAIN_SPEED from domain.PhysicsConstants",
	ReplaceWith("COMMON_MAIN_SPEED", "cz.vutbr.fit.interlockSim.domain.COMMON_MAIN_SPEED")
)
const val COMMON_MAIN_SPEED = cz.vutbr.fit.interlockSim.domain.COMMON_MAIN_SPEED

/**
 *
 */
const val UNSUPORTED_SWITCH_TYPES_MESSAGE = "unsuported switch types"

/**
 *
 */
val SUPPORTED_SIMPLE_SPATIAL_TYPES = arrayOf(Cell.SpatialType.HORIZONTAL, Cell.SpatialType.VERTICAL)

private val branches = SwitchMap<Set<Cell.Segment>>()
private val allConfs = SwitchMap<EnumUnorientedGraph<Cell.Segment, RailSwitch.Conf>>()

private fun putBranches() {
	putBranches(Type.SIMPLE_LEFT_FALSE, Cell.SpatialType.HORIZONTAL, Cell.Segment.E)
	putBranches(Type.SIMPLE_LEFT_FALSE, Cell.SpatialType.VERTICAL, Cell.Segment.G)
	putBranches(Type.SIMPLE_LEFT_TRUE, Cell.SpatialType.HORIZONTAL, Cell.Segment.D)
	putBranches(Type.SIMPLE_LEFT_TRUE, Cell.SpatialType.VERTICAL, Cell.Segment.B)

	putBranches(Type.SIMPLE_RIGHT_FALSE, Cell.SpatialType.HORIZONTAL, Cell.Segment.G)
	putBranches(Type.SIMPLE_RIGHT_FALSE, Cell.SpatialType.VERTICAL, Cell.Segment.D)
	putBranches(Type.SIMPLE_RIGHT_TRUE, Cell.SpatialType.HORIZONTAL, Cell.Segment.B)
	putBranches(Type.SIMPLE_RIGHT_TRUE, Cell.SpatialType.VERTICAL, Cell.Segment.E)

	for (t in Type.entries) {
		if (t.getKind() == RailSwitch.Kind.SIMPLE) {
			for (st in SUPPORTED_SIMPLE_SPATIAL_TYPES) {
				val confs = EnumUnorientedGraph<Cell.Segment, RailSwitch.Conf>(Cell.Segment::class.java)
				val merging = st.segments[if (t.getMergingPosition()) 0 else 1] // je v proti-directionu
				val mainDir = anti(merging)
				val set = branches.get(t, st)
				requireSimulation(set!!.size == 1) { "Branch set must have exactly 1 element: $set" }
				val branch = set.iterator().next()
				confs.put(merging, branch, RailSwitch.Conf.BRANCH)
				confs.put(merging, mainDir, RailSwitch.Conf.MAIN)
				allConfs.put(t, st, confs)
			}
		}
	}
}

private fun getBranchSegments(rSwitch: RailSwitch): Set<Cell.Segment> =
	branches.get(rSwitch.type, rSwitch.getSpatialType())!!

private fun putBranches(
	t: Type,
	st: Cell.SpatialType,
	first: Cell.Segment,
	vararg segments: Cell.Segment
) {
	branches.put(t, st, EnumSet.of(first, *segments) as Set<Cell.Segment>)
}
