/* Brno University of Technology
 * Faculty of Information Technology
 *
 * BSc Thesis  2006/2007
 *
 * Railway Interlocking Simulator
 *
 * Bedrich Hovorka
 */
package cz.vutbr.fit.interlockSim.objects.cells

import cz.vutbr.fit.interlockSim.exceptions.requireSimulation
import cz.vutbr.fit.interlockSim.exceptions.requireSimulationNotNull
import cz.vutbr.fit.interlockSim.exceptions.PathSeparatorChangeException
import cz.vutbr.fit.interlockSim.objects.cells.RailSwitch.Type
import cz.vutbr.fit.interlockSim.util.EnumUnorientedGraph
import io.github.oshai.kotlinlogging.KotlinLogging
import java.beans.PropertyChangeListener
import java.beans.PropertyChangeSupport
import java.util.EnumMap
import java.util.EnumSet
import java.util.Set
import java.util.Set as JavaSet

/**
 * Switch
 * CZ: "výhybka"
 */
class RailSwitch : NodeCell {
	enum class Kind(
		confs: JavaSet<Conf>
	) {
		/**
		 * switch with one branch
		 */
		SIMPLE(EnumSet.of(Conf.BRANCH, Conf.MAIN) as JavaSet<Conf>),

		/**
		 * not specified
		 */
		DUAL(EnumSet.noneOf(Conf::class.java) as JavaSet<Conf>); // NOT IMLEMENTED YET - EXTENSION

		@Suppress("UNCHECKED_CAST")
		private val possibleConfs: JavaSet<Conf> = confs

		fun getPossibleConfs(): JavaSet<Conf> = possibleConfs
	}

	enum class Conf {
		/**
		 * main directon
		 */
		MAIN,

		/**
		 * branch direction
		 */
		BRANCH
	}

	/**
	 *
	 * Type "smer odbocky"
	 *
	 */
	enum class Type(
		mergingOrientation: Boolean
	) {
		/**
		 *
		 */
		SIMPLE_RIGHT_FALSE(false),

		/**
		 *
		 */
		SIMPLE_RIGHT_TRUE(true),

		/**
		 *
		 */
		SIMPLE_LEFT_FALSE(false),

		/**
		 *
		 */
		SIMPLE_LEFT_TRUE(true);

		private val mergingPosition: Boolean
		private val kind: Kind

		init {
			// constructor only for simple kinds
			this.mergingPosition = mergingOrientation
			this.kind = Kind.SIMPLE
		}

		/**
		 * @return merging position (by simple kind)
		 */
		fun getMergingPosition(): Boolean = mergingPosition

		fun getKind(): Kind = kind
	}

	private val speeds: EnumMap<Conf, Double> = EnumMap<Conf, Double>(Conf::class.java)
	private val confs: EnumUnorientedGraph<Cell.Segment, Conf>
	val type: Type
	private var conf: Conf = Conf.MAIN
	private var locked: Boolean = false
	private val propertyChangeSupport: PropertyChangeSupport = PropertyChangeSupport(this)

	/**
	 * @param spatialType
	 * @param type
	 * @param mainSpeed
	 * @param branchSpeed
	 */
	constructor(
		spatialType: Cell.SpatialType,
		type: Type,
		mainSpeed: Double,
		branchSpeed: Double
	) : super(spatialType) {
		this.confs = allConfs.get(type, spatialType)
			?: throw IllegalArgumentException(UNSUPORTED_SWITCH_TYPES_MESSAGE)
		this.type = type
		speeds.put(Conf.BRANCH, branchSpeed)
		speeds.put(Conf.MAIN, mainSpeed)
	}

	/**
	 * @param spatialType
	 * @param type
	 */
	constructor(
		spatialType: Cell.SpatialType,
		type: Type
	) : this(spatialType, type, COMMON_MAIN_SPEED.toDouble(), COMMON_BRANCH_SPEED.toDouble())

	// Note: getType() is auto-generated by the 'val type' property

	/**
	 * @return current configuration (MAIN or BRANCH)
	 */
	fun getConf(): Conf = conf

	protected fun setConf(conf: Conf) {
		this.conf = conf
	}

	/**
	 * switch to second configuration
	 * @throws IllegalStateException if switch is locked (safety property SI-5)
	 */
	fun changeConf() {
		if (locked) {
			throw IllegalStateException(
				"Cannot change switch configuration while locked " +
					"(safety SI-5: switch cannot toggle during train movement)"
			)
		}
		requireSimulationNotNull(conf) { "Switch configuration must not be null" }
		val oldConf = conf
		conf = if (conf == Conf.MAIN) Conf.BRANCH else Conf.MAIN
		logger.info {
			"${jDisco.Process.time()} Switch ${this.hashCode()} position change: $oldConf -> $conf"
		}
	}

	override fun cancelPathSetup(
		from: Cell.Segment?,
		to: Cell.Segment?
	) {
		val pathConf = getPathConfWithException(from, to)
		if (pathConf != getConf()) {
			throw PathSeparatorChangeException("cancelPathSetup: Switch is not configured (neccesarry except?)", this)
		}
	}

	override fun allowedSpeed(): Double {
		val double1 = speeds.get(getConf())
		requireSimulationNotNull(double1) { "Speed for configuration must not be null: speeds=$speeds" }
		return double1!!.toDouble()
	}

	@Suppress("OVERRIDE_BY_SYNTHETIC")
	override fun joins(): Set<Cell.Segment> {
		// Parent Cell interface expects java.util.Set, and joinsOnLine() returns that
		val joins = joinsOnLine()
		joins.addAll(getBranchSegments())
		return joins
	}

	override fun getFollowingSegment(from: Cell.Segment?): Cell.Segment? {
		val map = confs.getJoinedNodesAndEdges(from)
		for (e in (map as Map<*, *>).entries) {
			@Suppress("UNCHECKED_CAST")
			val entry = e as Map.Entry<Cell.Segment, Conf>
			if (entry.value == getConf()) return entry.key
		}
		return null
	}

	/**
	 * @return directions of branchs
	 */
	fun getBranchSegments(): Set<Cell.Segment> = getBranchSegments(this)

	override fun setUpPath(
		from: Cell.Segment?,
		to: Cell.Segment?,
		allowedSpeed: Double
	) {
		val newConf = getPathConfWithException(from, to)
		logger.info {
			"${jDisco.Process.time()} Switch ${this.hashCode()} path setup: from=$from to=$to, " +
				"conf=$newConf, allowedSpeed=$allowedSpeed"
		}
		setConf(newConf)
	}

	@Throws(PathSeparatorChangeException::class)
	private fun getPathConfWithException(
		from: Cell.Segment?,
		to: Cell.Segment?
	): Conf {
		// Java would NPE here if from or to are null - we make it explicit
		if (from == null || to == null) {
			throw PathSeparatorChangeException("switch segments cannot be null", this)
		}
		val pathConf = confs.get(from, to)
		if (pathConf == null) throw PathSeparatorChangeException("switch doesn't join this segments", this)
		return pathConf
	}

	@Suppress("OVERRIDE_BY_SYNTHETIC")
	override fun possibleFollowers(from: Cell.Segment): Set<Cell.Segment> {
		val map = confs.getJoinedNodesAndEdges(from)
		@Suppress("UNCHECKED_CAST")
		return (map as Map<Cell.Segment, *>).keys as Set<Cell.Segment>
	}

	/**
	 * Locks the switch to prevent position changes during train movement.
	 * Safety property SI-5: Switch cannot toggle during train movement.
	 */
	fun lock() {
		val oldLocked = locked
		locked = true
		logger.debug {
			"${jDisco.Process.time()} Switch ${this.hashCode()} locked"
		}
		propertyChangeSupport.firePropertyChange("locked", oldLocked, locked)
	}

	/**
	 * Unlocks the switch to allow position changes.
	 * Safety property SI-5: Switch cannot toggle during train movement.
	 */
	fun unlock() {
		val oldLocked = locked
		locked = false
		logger.debug {
			"${jDisco.Process.time()} Switch ${this.hashCode()} unlocked"
		}
		propertyChangeSupport.firePropertyChange("locked", oldLocked, locked)
	}

	/**
	 * @return true if switch is locked, false otherwise
	 */
	fun isLocked(): Boolean = locked

	/**
	 * Convenience method to check if switch is in MAIN (normal) configuration.
	 *
	 * @return true if configuration is MAIN, false otherwise
	 */
	fun isNormal(): Boolean = conf == Conf.MAIN

	/**
	 * Convenience method to check if switch is in BRANCH (reverse) configuration.
	 *
	 * @return true if configuration is BRANCH, false otherwise
	 */
	fun isReverse(): Boolean = conf == Conf.BRANCH

	/**
	 * Registers a PropertyChangeListener to be notified of switch state changes.
	 *
	 * @param listener the PropertyChangeListener to add
	 */
	fun addPropertyChangeListener(listener: PropertyChangeListener) {
		propertyChangeSupport.addPropertyChangeListener(listener)
	}

	/**
	 * Unregisters a PropertyChangeListener from receiving switch state change notifications.
	 *
	 * @param listener the PropertyChangeListener to remove
	 */
	fun removePropertyChangeListener(listener: PropertyChangeListener) {
		propertyChangeSupport.removePropertyChangeListener(listener)
	}

	companion object {
		init {
			putBranches()
		}
	}
}

private class SwitchMap<V> : EnumMap<Type, EnumMap<Cell.SpatialType, V>>(Type::class.java) {
	fun put(
		t: Type,
		st: Cell.SpatialType,
		v: V
	) {
		var subMap = get(t)
		if (subMap == null) {
			subMap = EnumMap<Cell.SpatialType, V>(Cell.SpatialType::class.java)
			put(t, subMap)
		}
		subMap.put(st, v)
	}

	fun get(
		t: Type,
		st: Cell.SpatialType
	): V? {
		val subMap = get(t)
		if (subMap == null) return null
		return subMap.get(st)
	}
}

private val logger = KotlinLogging.logger {}

/**
 * allowed speed
 */
const val COMMON_BRANCH_SPEED = 13

/**
 * allowed speed
 */
const val COMMON_MAIN_SPEED = 30

/**
 *
 */
const val UNSUPORTED_SWITCH_TYPES_MESSAGE = "unsuported switch types"

/**
 *
 */
val SUPPORTED_SIMPLE_SPATIAL_TYPES = arrayOf(Cell.SpatialType.HORIZONTAL, Cell.SpatialType.VERTICAL)

private val branches = SwitchMap<Set<Cell.Segment>>()
private val allConfs = SwitchMap<EnumUnorientedGraph<Cell.Segment, RailSwitch.Conf>>()

private fun putBranches() {
	putBranches(Type.SIMPLE_LEFT_FALSE, Cell.SpatialType.HORIZONTAL, Cell.Segment.E)
	putBranches(Type.SIMPLE_LEFT_FALSE, Cell.SpatialType.VERTICAL, Cell.Segment.G)
	putBranches(Type.SIMPLE_LEFT_TRUE, Cell.SpatialType.HORIZONTAL, Cell.Segment.D)
	putBranches(Type.SIMPLE_LEFT_TRUE, Cell.SpatialType.VERTICAL, Cell.Segment.B)

	putBranches(Type.SIMPLE_RIGHT_FALSE, Cell.SpatialType.HORIZONTAL, Cell.Segment.G)
	putBranches(Type.SIMPLE_RIGHT_FALSE, Cell.SpatialType.VERTICAL, Cell.Segment.D)
	putBranches(Type.SIMPLE_RIGHT_TRUE, Cell.SpatialType.HORIZONTAL, Cell.Segment.B)
	putBranches(Type.SIMPLE_RIGHT_TRUE, Cell.SpatialType.VERTICAL, Cell.Segment.E)

	for (t in Type.entries) {
		if (t.getKind() == RailSwitch.Kind.SIMPLE) {
			for (st in SUPPORTED_SIMPLE_SPATIAL_TYPES) {
				val confs = EnumUnorientedGraph<Cell.Segment, RailSwitch.Conf>(Cell.Segment::class.java)
				val merging = st.segments[if (t.getMergingPosition()) 0 else 1] // je v proti-directionu
				val mainDir = anti(merging)
				val set = branches.get(t, st)
				requireSimulation(set!!.size == 1) { "Branch set must have exactly 1 element: $set" }
				val branch = set.iterator().next()
				confs.put(merging, branch, RailSwitch.Conf.BRANCH)
				confs.put(merging, mainDir, RailSwitch.Conf.MAIN)
				allConfs.put(t, st, confs)
			}
		}
	}
}

private fun getBranchSegments(rSwitch: RailSwitch): Set<Cell.Segment> =
	branches.get(rSwitch.type, rSwitch.getSpatialType())!!

private fun putBranches(
	t: Type,
	st: Cell.SpatialType,
	first: Cell.Segment,
	vararg segments: Cell.Segment
) {
	branches.put(t, st, EnumSet.of(first, *segments) as Set<Cell.Segment>)
}

