{
  "formatVersion": "1.1",
  "component": {
    "group": "cz.hovorka.kdisco",
    "module": "kdisco-core",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kdisco-core-metadata-0.4.0.jar",
          "url": "kdisco-core-0.4.0.jar",
          "size": 16780,
          "sha512": "f3ab194fa285a049048005dc29fd0bddac06dadaf4e17dc4dbea22070b1053116fae953019b15f8b936c8ccc7f64cb4f3055beb0a8737fedcbd817a8ee28d8f2",
          "sha256": "59a1cda9657cfdb021fb7b6825ac7d97eea1ee05aa164c6866b8b0a9023cbbb9",
          "sha1": "0e7f5a676faaceb4a587e96410544b531ac3f4c6",
          "md5": "fde6e8c24e644ebcdf54c1504c5c9e23"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kdisco-core-kotlin-0.4.0-sources.jar",
          "url": "kdisco-core-0.4.0-sources.jar",
          "size": 24475,
          "sha512": "4c255096d4a736b185a9e38bbab537be6c6cfd29d0da13ba9e89aa95490b93be56656844baa04885eebc9193dd27185feb6bc7b869578812ec22f5f89ddf43a0",
          "sha256": "27410b503cb8cf9a78d4428790449a0785413acbca91dd0864c93f159a4eb28f",
          "sha1": "d2a99cbf43744c46bf3ac127f610c0a2f3edd508",
          "md5": "c47e23e48dec6d087255023f114dcc0e"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kdisco-core-js/0.4.0/kdisco-core-js-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-js",
        "version": "0.4.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kdisco-core-js/0.4.0/kdisco-core-js-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-js",
        "version": "0.4.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kdisco-core-js/0.4.0/kdisco-core-js-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-js",
        "version": "0.4.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kdisco-core-jvm/0.4.0/kdisco-core-jvm-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-jvm",
        "version": "0.4.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kdisco-core-jvm/0.4.0/kdisco-core-jvm-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-jvm",
        "version": "0.4.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kdisco-core-jvm/0.4.0/kdisco-core-jvm-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-jvm",
        "version": "0.4.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kdisco-core-linuxx64/0.4.0/kdisco-core-linuxx64-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-linuxx64",
        "version": "0.4.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kdisco-core-linuxx64/0.4.0/kdisco-core-linuxx64-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-linuxx64",
        "version": "0.4.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kdisco-core-macosarm64/0.4.0/kdisco-core-macosarm64-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-macosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kdisco-core-macosarm64/0.4.0/kdisco-core-macosarm64-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-macosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kdisco-core-macosarm64/0.4.0/kdisco-core-macosarm64-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-macosarm64",
        "version": "0.4.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kdisco-core-macosx64/0.4.0/kdisco-core-macosx64-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-macosx64",
        "version": "0.4.0"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kdisco-core-macosx64/0.4.0/kdisco-core-macosx64-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-macosx64",
        "version": "0.4.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kdisco-core-macosx64/0.4.0/kdisco-core-macosx64-0.4.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-core-macosx64",
        "version": "0.4.0"
      }
    }
  ]
}
