{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kdisco-core/0.5.0/kdisco-core-0.5.0.module",
    "group": "cz.hovorka.kdisco",
    "module": "kdisco-core",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kdisco-core-js-0.5.0.klib",
          "url": "kdisco-core-js-0.5.0.klib",
          "size": 80870,
          "sha512": "99a9b20dc498194c44be57279c3018cbdc8f1bfd60d9855cd45e77c3d93bc99ce475beaa2d96b621f4b2aff08f77e06515695d648f2b5fb411f4844df191095c",
          "sha256": "b52956e99970becbc29c37a4c7c1fee8616de3ee981b58c5e152656263f266f2",
          "sha1": "7ee842f37f7c041f4668c7dbaae98681a7f4c01e",
          "md5": "007a7ebd79a7c063ea97d14e21b6ec6c"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kdisco-core-js-0.5.0.klib",
          "url": "kdisco-core-js-0.5.0.klib",
          "size": 80870,
          "sha512": "99a9b20dc498194c44be57279c3018cbdc8f1bfd60d9855cd45e77c3d93bc99ce475beaa2d96b621f4b2aff08f77e06515695d648f2b5fb411f4844df191095c",
          "sha256": "b52956e99970becbc29c37a4c7c1fee8616de3ee981b58c5e152656263f266f2",
          "sha1": "7ee842f37f7c041f4668c7dbaae98681a7f4c01e",
          "md5": "007a7ebd79a7c063ea97d14e21b6ec6c"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kdisco-core-js-0.5.0-sources.jar",
          "url": "kdisco-core-js-0.5.0-sources.jar",
          "size": 24661,
          "sha512": "dbbbf98a1ef9e8daefcf606bec40222dee3433c256afa926fec7b21cb133ed0f062c6986ca1557ed99b285829086e6400e7d659f73a0529409cb27a4a85d1bdb",
          "sha256": "e74e65c86f58c4488d0046f6ccabe0ad0d48072e7ce37856da67a4d02a653843",
          "sha1": "b1df670cfa8f912dd4d68e3c2b3198b74e4c233a",
          "md5": "48c178cbc83915fbd547c7785082dfb9"
        }
      ]
    }
  ]
}
