/* Brno University of Technology
 * Faculty of Information Technology
 *
 * BSc Thesis  2006/2007
 *
 * Railway Interlocking Simulator
 *
 * Bedrich Hovorka
 */
package cz.vutbr.fit.interlockSim.dispatcher.agents.tools

import cz.vutbr.fit.interlockSim.dispatcher.agents.DomainTool
import cz.vutbr.fit.interlockSim.dispatcher.agents.DomainToolParameter
import cz.vutbr.fit.interlockSim.dispatcher.agents.ToolResult
import cz.vutbr.fit.interlockSim.ports.DispatchLoopSensorPort
import io.github.oshai.kotlinlogging.KotlinLogging

/**
 * Sensor tool exposing [DispatchLoopSensorPort.getQueuedTrains] to agent consumers (SP4.1, Issue #563).
 *
 * Returns the list of trains currently queued for dispatch approval — i.e. trains that have been
 * generated by the ShuntingLoop but not yet admitted to the active network. Each entry carries
 * the train's id and its intended destination InOut name.
 *
 * An agent reads this list to decide which trains to approve via [ApproveTrainTool].
 *
 * The result is a **snapshot** from the latest tick published by the simulation shell; it may
 * be one tick stale relative to current simulation time, which is acceptable for dispatch
 * decision making.
 *
 * @param sensorPort Dispatch-loop sensor port for this context (injected per simulation)
 *
 * @since Issue #563 (SP4.1 — Goal 10 reactive-train agent)
 */
class QueuedTrainsTool(
	private val sensorPort: DispatchLoopSensorPort
) : DomainTool {
	companion object {
		private val logger = KotlinLogging.logger {}
	}

	override val name: String = "queued_trains"

	override val description: String =
		"Return all trains currently queued for dispatch — generated but not yet approved onto the " +
			"active network. Each entry contains the train id and its intended destination InOut name. " +
			"An agent calls this to discover which trains are waiting and then issues approve_train."

	override val parameters: List<DomainToolParameter> = emptyList()

	override suspend fun execute(args: Map<String, Any?>): ToolResult {
		logger.debug { "QueuedTrainsTool.execute" }
		return runCatching { sensorPort.getQueuedTrains() }
			.fold({ ToolResult.Success(it) }, { ToolResult.Error("queued_trains failed: ${it.message}", it) })
	}
}
