/* Brno University of Technology
 * Faculty of Information Technology
 *
 * BSc Thesis  2006/2007
 *
 * Railway Interlocking Simulator
 *
 * Bedrich Hovorka
 */
package cz.vutbr.fit.interlockSim.objects.cells

import cz.vutbr.fit.interlockSim.exceptions.requireSimulation
import cz.vutbr.fit.interlockSim.objects.cells.RailSwitch.Type
import cz.vutbr.fit.interlockSim.objects.core.Cell
import cz.vutbr.fit.interlockSim.objects.core.anti
import cz.vutbr.fit.interlockSim.util.EnumUnorientedGraph
import io.github.oshai.kotlinlogging.KotlinLogging

/**
 * Switch
 * CZ: "výhybka"
 */
class RailSwitch : NodeCell {
	enum class Kind(
		confs: Set<Conf>
	) {
		/**
		 * switch with one branch
		 */
		SIMPLE(setOf(Conf.BRANCH, Conf.MAIN)),

		/**
		 * not specified
		 */
		DUAL(emptySet()); // NOT IMLEMENTED YET - EXTENSION

		@Suppress("UNCHECKED_CAST")
		private val possibleConfs: Set<Conf> = confs

		fun getPossibleConfs(): Set<Conf> = possibleConfs
	}

	enum class Conf {
		/**
		 * main directon
		 */
		MAIN,

		/**
		 * branch direction
		 */
		BRANCH
	}

	/**
	 *
	 * Type "smer odbocky"
	 *
	 */
	enum class Type(
		mergingOrientation: Boolean
	) {
		/**
		 *
		 */
		SIMPLE_RIGHT_FALSE(false),

		/**
		 *
		 */
		SIMPLE_RIGHT_TRUE(true),

		/**
		 *
		 */
		SIMPLE_LEFT_FALSE(false),

		/**
		 *
		 */
		SIMPLE_LEFT_TRUE(true);

		private val mergingPosition: Boolean
		private val kind: Kind

		init {
			// constructor only for simple kinds
			this.mergingPosition = mergingOrientation
			this.kind = Kind.SIMPLE
		}

		/**
		 * @return merging position (by simple kind)
		 */
		fun getMergingPosition(): Boolean = mergingPosition

		fun getKind(): Kind = kind
	}

	val speeds: HashMap<Conf, Double> = HashMap()
	val confs: EnumUnorientedGraph<Cell.Segment, Conf>
	val type: Type

	/**
	 * @param name Name of this switch (empty string means unnamed)
	 * @param spatialType
	 * @param type
	 * @param mainSpeed
	 * @param branchSpeed
	 */
	constructor(
		name: String,
		spatialType: Cell.SpatialType,
		type: Type,
		mainSpeed: Double,
		branchSpeed: Double
	) : super(spatialType, name) {		this.confs = allConfs.get(type, spatialType)
			?: throw IllegalArgumentException(UNSUPORTED_SWITCH_TYPES_MESSAGE)
		this.type = type
		speeds.put(Conf.BRANCH, branchSpeed)
		speeds.put(Conf.MAIN, mainSpeed)
	}

	/**
	 * @param spatialType
	 * @param type
	 * @param mainSpeed
	 * @param branchSpeed
	 */
	constructor(
		spatialType: Cell.SpatialType,
		type: Type,
		mainSpeed: Double,
		branchSpeed: Double
	) : this("", spatialType, type, mainSpeed, branchSpeed)

	/**
	 * @param spatialType
	 * @param type
	 */
	constructor(
		spatialType: Cell.SpatialType,
		type: Type
	) : this("", spatialType, type, COMMON_MAIN_SPEED.toDouble(), COMMON_BRANCH_SPEED.toDouble())

	/**
	 * Constructor accepting optional name, spatialType, and type.
	 * Used by XML parser when name attribute is present.
	 *
	 * Example XML:
	 * ```xml
	 * <RailSwitch X="10" Y="15" SpatialType="HORIZONTAL"
	 *             Type="SIMPLE_LEFT_TRUE" name="switch_junction_A"/>
	 * ```
	 *
	 * @param name Optional name for the switch (alphanumeric, -, _, max 50 chars).
	 *             Null or empty = auto-generated name.
	 * @param spatialType Spatial type (HORIZONTAL/VERTICAL)
	 * @param type Switch type (SIMPLE_LEFT_FALSE, SIMPLE_RIGHT_TRUE, etc.)
	 * @since 2026-01 (Issue #296 Phase 4, Issue #306)
	 */
	constructor(
		name: String?,
		spatialType: Cell.SpatialType,
		type: Type
	) : this(name ?: "", spatialType, type, COMMON_MAIN_SPEED.toDouble(), COMMON_BRANCH_SPEED.toDouble())

	// Note: getType() is auto-generated by the 'val type' property

	/**
	 * Create a copy of this switch with the given name.
	 *
	 * @param newName The new name for the copy
	 * @return A new RailSwitch with the updated name
	 */
	override fun withName(newName: String): RailSwitch = RailSwitch(newName, getSpatialType(), type)

	/**
	 * Implementation of isSwitch() for DynamicRailSwitch.
	 * Returns true since this is a switch.
	 */
	override fun isSwitch(): Boolean = true

	@Suppress("OVERRIDE_BY_SYNTHETIC")
	override fun joins(): Set<Cell.Segment> {
		// Parent Cell interface expects Set, and joinsOnLine() returns MutableSet
		val joins = joinsOnLine()
		joins.addAll(getBranchSegments())
		return joins
	}

	/**
	 * @return directions of branchs
	 */
	fun getBranchSegments(): Set<Cell.Segment> = getBranchSegments(this)

	@Suppress("OVERRIDE_BY_SYNTHETIC")
	override fun possibleFollowers(from: Cell.Segment): Set<Cell.Segment> {
		val map = confs.getJoinedNodesAndEdges(from)
		@Suppress("UNCHECKED_CAST")
		return (map as Map<Cell.Segment, *>).keys
	}

	companion object {
		init {
			putBranches()
		}
	}
}

private class SwitchMap<V> {
	private val map: HashMap<Type, HashMap<Cell.SpatialType, V>> = HashMap()

	fun put(
		t: Type,
		st: Cell.SpatialType,
		v: V
	) {
		map.getOrPut(t) { HashMap() }[st] = v
	}

	fun get(
		t: Type,
		st: Cell.SpatialType
	): V? = map[t]?.get(st)
}

private val logger = KotlinLogging.logger {}

/**
 * allowed speed
 * @deprecated Use [cz.vutbr.fit.interlockSim.domain.COMMON_BRANCH_SPEED] from domain.PhysicsConstants
 */
@Deprecated(
	"Use COMMON_BRANCH_SPEED from domain.PhysicsConstants",
	ReplaceWith("COMMON_BRANCH_SPEED", "cz.vutbr.fit.interlockSim.domain.COMMON_BRANCH_SPEED")
)
const val COMMON_BRANCH_SPEED = cz.vutbr.fit.interlockSim.domain.COMMON_BRANCH_SPEED

/**
 * allowed speed
 * @deprecated Use [cz.vutbr.fit.interlockSim.domain.COMMON_MAIN_SPEED] from domain.PhysicsConstants
 */
@Deprecated(
	"Use COMMON_MAIN_SPEED from domain.PhysicsConstants",
	ReplaceWith("COMMON_MAIN_SPEED", "cz.vutbr.fit.interlockSim.domain.COMMON_MAIN_SPEED")
)
const val COMMON_MAIN_SPEED = cz.vutbr.fit.interlockSim.domain.COMMON_MAIN_SPEED

/**
 *
 */
const val UNSUPORTED_SWITCH_TYPES_MESSAGE = "unsuported switch types"

/**
 *
 */
val SUPPORTED_SIMPLE_SPATIAL_TYPES = arrayOf(Cell.SpatialType.HORIZONTAL, Cell.SpatialType.VERTICAL)

private val branches = SwitchMap<Set<Cell.Segment>>()
private val allConfs = SwitchMap<EnumUnorientedGraph<Cell.Segment, RailSwitch.Conf>>()

private fun putBranches() {
	putBranches(Type.SIMPLE_LEFT_FALSE, Cell.SpatialType.HORIZONTAL, Cell.Segment.E)
	putBranches(Type.SIMPLE_LEFT_FALSE, Cell.SpatialType.VERTICAL, Cell.Segment.G)
	putBranches(Type.SIMPLE_LEFT_TRUE, Cell.SpatialType.HORIZONTAL, Cell.Segment.D)
	putBranches(Type.SIMPLE_LEFT_TRUE, Cell.SpatialType.VERTICAL, Cell.Segment.B)

	putBranches(Type.SIMPLE_RIGHT_FALSE, Cell.SpatialType.HORIZONTAL, Cell.Segment.G)
	putBranches(Type.SIMPLE_RIGHT_FALSE, Cell.SpatialType.VERTICAL, Cell.Segment.D)
	putBranches(Type.SIMPLE_RIGHT_TRUE, Cell.SpatialType.HORIZONTAL, Cell.Segment.B)
	putBranches(Type.SIMPLE_RIGHT_TRUE, Cell.SpatialType.VERTICAL, Cell.Segment.E)

	for (t in Type.entries) {
		if (t.getKind() == RailSwitch.Kind.SIMPLE) {
			for (st in SUPPORTED_SIMPLE_SPATIAL_TYPES) {
				val confs = EnumUnorientedGraph<Cell.Segment, RailSwitch.Conf>()
				val merging = st.segments[if (t.getMergingPosition()) 0 else 1] // je v proti-directionu
				val mainDir = anti(merging)
				val set = branches.get(t, st)
				requireSimulation(set!!.size == 1) { "Branch set must have exactly 1 element: $set" }
				val branch = set.iterator().next()
				confs.put(merging, branch, RailSwitch.Conf.BRANCH)
				confs.put(merging, mainDir, RailSwitch.Conf.MAIN)
				allConfs.put(t, st, confs)
			}
		}
	}
}

private fun getBranchSegments(rSwitch: RailSwitch): Set<Cell.Segment> =
	branches.get(rSwitch.type, rSwitch.getSpatialType())!!

private fun putBranches(
	t: Type,
	st: Cell.SpatialType,
	first: Cell.Segment,
	vararg segments: Cell.Segment
) {
	branches.put(t, st, setOf(first, *segments))
}
