{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kdisco-koin/0.5.0/kdisco-koin-0.5.0.module",
    "group": "cz.hovorka.kdisco",
    "module": "kdisco-koin",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "cz.hovorka.kdisco",
          "module": "kdisco-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kdisco-koin-jvm-0.5.0.jar",
          "url": "kdisco-koin-jvm-0.5.0.jar",
          "size": 23489,
          "sha512": "b1a4f922398f26f9b5637c8f9f9c73e91aa05ca43cf673318ed7583163f9fc9290cc7d946226b145837ce5e83ecd8a95f62e019d73d857f3018deffc4cdcc972",
          "sha256": "ec887f9a5c51e3f3cf529d640a0d1cbfe13c9d49d7a1195a9e85b9020bfef052",
          "sha1": "7c3d72241fd4d578460cefea1b55febf18f8922a",
          "md5": "2619aee15febb9e07b7cad3a957f888e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "cz.hovorka.kdisco",
          "module": "kdisco-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kdisco-koin-jvm-0.5.0.jar",
          "url": "kdisco-koin-jvm-0.5.0.jar",
          "size": 23489,
          "sha512": "b1a4f922398f26f9b5637c8f9f9c73e91aa05ca43cf673318ed7583163f9fc9290cc7d946226b145837ce5e83ecd8a95f62e019d73d857f3018deffc4cdcc972",
          "sha256": "ec887f9a5c51e3f3cf529d640a0d1cbfe13c9d49d7a1195a9e85b9020bfef052",
          "sha1": "7c3d72241fd4d578460cefea1b55febf18f8922a",
          "md5": "2619aee15febb9e07b7cad3a957f888e"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kdisco-koin-jvm-0.5.0-sources.jar",
          "url": "kdisco-koin-jvm-0.5.0-sources.jar",
          "size": 7008,
          "sha512": "27f52baf77161e71d3a8d86e17d7c8c407be58af216c9d437d7c52203e8ccb9835a84e336bbc45a02e30c4ec43dda5dbd9e770b9bc45c2800e24375e871fcaaa",
          "sha256": "0e13bda0adadf7cd945e3156f5bd0d283d6e53a8e70ef8ca6ec0e21121212fc8",
          "sha1": "7b249299fa008bb3b12fdfeb75cf1630cd1140f3",
          "md5": "d816da2a3326f5f4302ffde6cc9e861c"
        }
      ]
    }
  ]
}
