{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kdisco-core/0.3.0/kdisco-core-0.3.0.module",
    "group": "cz.hovorka.kdisco",
    "module": "kdisco-core",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kdisco-core-linuxX64Main-0.3.0.klib",
          "url": "kdisco-core-linuxx64-0.3.0.klib",
          "size": 76357,
          "sha512": "35820d5232ec0ae107577f5cd49ffa73819043da97f1d6d4369e547b9542537907b77453bfaead19afe6921481a10befa478f0e30b6253da85813ee7d23e1054",
          "sha256": "f67277ab27d03fd638a28463d97a06f944b7543837d915aaa842af6534de2862",
          "sha1": "2639e834214effa7cdc40aa90e94bb232574167b",
          "md5": "cb0eeb1f787dbb0e5fe7b37c940258bb"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kdisco-core-linuxx64-0.3.0-sources.jar",
          "url": "kdisco-core-linuxx64-0.3.0-sources.jar",
          "size": 23969,
          "sha512": "e257f5a0103aa2e0ff8c9f02d63e8809c17657cc5587d9ad4f862b823731ef8b66bdcdd727aa31ff42f748ddc2671fc0abfdc99303fde037cc5af15f0c3af8fa",
          "sha256": "0aedd2718f311b7e301c4b3ba63e23bcd930ad3067346c1c83dafc41f016b978",
          "sha1": "a88ca9835cf44c426a1d1669a2485f7454eee7f3",
          "md5": "7631af55db5b3b802c10492fe3d8a951"
        }
      ]
    }
  ]
}
