{
  "formatVersion": "1.1",
  "component": {
    "group": "cz.hovorka.kdisco",
    "module": "kdisco-koin",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "cz.hovorka.kdisco",
          "module": "kdisco-core",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "kdisco-koin-metadata-0.3.0.jar",
          "url": "kdisco-koin-0.3.0.jar",
          "size": 689,
          "sha512": "a9ea4418e607bb6003e8f06b3a53174db79c9769b0f92529f7869a2c4c3ae54c1e61d23d4e3d1986bb03b96f4c771e7ac76e013c9bf4aa9a8f8836b05a6e225e",
          "sha256": "dcb65bbf45c6233a42d0d987e5704cd52c189e50277552ad120a195dbe6db3d2",
          "sha1": "6dc7e81d09e59a0bd36fd7ce35795605acc1b352",
          "md5": "079c00d2e79c4ff3b03def7be8cbd12f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kdisco-koin-kotlin-0.3.0-sources.jar",
          "url": "kdisco-koin-0.3.0-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kdisco-koin-jvm/0.3.0/kdisco-koin-jvm-0.3.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-koin-jvm",
        "version": "0.3.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kdisco-koin-jvm/0.3.0/kdisco-koin-jvm-0.3.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-koin-jvm",
        "version": "0.3.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kdisco-koin-jvm/0.3.0/kdisco-koin-jvm-0.3.0.module",
        "group": "cz.hovorka.kdisco",
        "module": "kdisco-koin-jvm",
        "version": "0.3.0"
      }
    }
  ]
}
